main:
- name: Education
  url: /education/
  weight: 1

- name: Experience
  url: /experience/
  weight: 2

- name: Publications
  url: /publications/
  weight: 3

- name: Teaching
  url: /teaching/
  weight: 4

- name: Research Interests
  url: /research/
  weight: 5

social:
- name: email
  url: mailto:subrakn21@iitk.ac.in
  weight: 1
  params:
    icon: fas fa-envelope

- name: LinkedIn
  url: https://linkedin.com/in/knsubrahmanya11
  weight: 2
  params:
    icon: fab fa-linkedin
