firstName: Subrahmanya
lastName: Keremane Narayan

email: subrakn21@iitk.ac.in

description: Albert Einstein's personal website powered by the Academic Folio theme

maxWidth: 1024px

navbarTitle: true # displays the title in the navbar on non home pages

footerLastUpdated: true

socialNavbar: true # show social icons on navbar
socialHomePage: true # show social icons on the home page

colorTheme: blue # choose a theme from `data/themes` folder
